//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.API.API_CLS
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_RESPONSE_ERRORS
    {
        public long ErrID { get; set; }
        public string Nombre { get; set; }
        public string Mensaje { get; set; }
        public bool IndTipo { get; set; }
        public byte Estado { get; set; }
    }
}
