//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.API.API_CLS
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_USUARIOS
    {
        public string Username { get; set; }
        public string API_TOKEN { get; set; }
        public string API_SECRET { get; set; }
        public int Estado { get; set; }
        public System.DateTime VigenciaD { get; set; }
        public System.DateTime VigenciaH { get; set; }
        public bool IndValVigFecha { get; set; }
    }
}
