//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.API.API_CLS
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_PROF_ACCESOS
    {
        public long AccID { get; set; }
        public long AccIDP { get; set; }
        public string Ico { get; set; }
        public string Nombre { get; set; }
        public string URL_C { get; set; }
        public string URL_V { get; set; }
        public long AccOrden { get; set; }
    }
}
