//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.API.API_CLS
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_PROY_DET
    {
        public long ProyID { get; set; }
        public int DetID { get; set; }
        public string Nombre { get; set; }
        public string URL { get; set; }
        public long HAtrID { get; set; }
        public long CTAtrID { get; set; }
        public int Estado { get; set; }
        public string UsuarioDIG { get; set; }
        public System.DateTime FechaDIG { get; set; }
        public string Descrip { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
    }
}
