//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.API.API_CLS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class API_CLS : DbContext
    {
        public API_CLS()
            : base("name=API_CLS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<API_ATTR_CONT_TYPE> API_ATTR_CONT_TYPE { get; set; }
        public virtual DbSet<API_ATTR_HTTP> API_ATTR_HTTP { get; set; }
        public virtual DbSet<API_PROF_ACCESOS> API_PROF_ACCESOS { get; set; }
        public virtual DbSet<API_PROF_USERS> API_PROF_USERS { get; set; }
        public virtual DbSet<API_USUARIOS_PROY> API_USUARIOS_PROY { get; set; }
        public virtual DbSet<API_USUARIOS_PROY_DET> API_USUARIOS_PROY_DET { get; set; }
        public virtual DbSet<API_USUARIOS> API_USUARIOS { get; set; }
        public virtual DbSet<API_RESPONSE_ERRORS> API_RESPONSE_ERRORS { get; set; }
        public virtual DbSet<API_PROY_CAB> API_PROY_CAB { get; set; }
        public virtual DbSet<API_PROY_DET> API_PROY_DET { get; set; }
    }
}
