//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.GET_POINT.GP_CLS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int EmpId { get; set; }
        public string Rut { get; set; }
        public int EmpOwner { get; set; }
        public string RazonSocial { get; set; }
        public int Giro { get; set; }
        public string NombreFantasia { get; set; }
        public string Direccion { get; set; }
        public int Region { get; set; }
        public int Ciudad { get; set; }
        public int Comuna { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string Mail1 { get; set; }
        public string Mail2 { get; set; }
        public string Web { get; set; }
        public int Tipo { get; set; }
        public int ConfigId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaAct { get; set; }
        public string UsuarioAct { get; set; }
        public byte Estado { get; set; }
        public string CodigoExt { get; set; }
        public short ValidaRut { get; set; }
    }
}
