//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.GET_POINT.GP_CLS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Rut { get; set; }
        public string RutEmpresa { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPat { get; set; }
        public string ApellidoMat { get; set; }
        public string Direccion { get; set; }
        public int Region { get; set; }
        public int Ciudad { get; set; }
        public int Comuna { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoOficina { get; set; }
        public string Movil { get; set; }
        public string Fax { get; set; }
        public string Mail1 { get; set; }
        public string Mail2 { get; set; }
        public int Estado { get; set; }
        public int Nivel { get; set; }
        public byte UsuarioFin700 { get; set; }
        public System.DateTime FecUltConx { get; set; }
        public string IPUltConx { get; set; }
        public short Intentos { get; set; }
        public System.DateTime FecUltInt { get; set; }
        public byte[] PWD { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Usuario1 { get; set; }
        public System.DateTime FechaAct { get; set; }
        public string UsuarioAct { get; set; }
        public byte[] PWD2 { get; set; }
    }
}
