DROP PROCEDURE		SP_GEN_API_PROF_USERS_LOGIN_NEW_PW
go
CREATE PROCEDURE	SP_GEN_API_PROF_USERS_LOGIN_NEW_PW
@PHRASE	CHAR(36)
,@PW	CHAR(15)
AS
BEGIN
DECLARE 
@AUX_RESPUESTA VARBINARY(MAX)
Select @AUX_RESPUESTA= ENCRYPTBYPASSPHRASE(RTRIM(@PHRASE),RTRIM(@PW))
Select @AUX_RESPUESTA As PW

END


