DROP PROCEDURE	SP_SEL_API_GRANT_LIST_USUARIOS
go
CREATE PROCEDURE	SP_SEL_API_GRANT_LIST_USUARIOS
@RUTEMPRESA		CHAR(12)
,@USERNAME		CHAR(15)
,@APELLIDOPAT	CHAR(30)
,@ESTADO		INT
,@INDTOKEN		INT
,@TOKEN			CHAR(36)
AS
BEGIN

	SELECT 
	U.UserName
	,U.Nombres
	,U.ApellidoPat
	,U.ApellidoMat
	,E.Rut
	,E.RazonSocial
	,ISNULL((SELECT COUNT(1) FROM API_USUARIOS API(NOLOCK) WHERE API.USERNAME = U.USERNAME),0) AS COUNT_TOKEN
	FROM	Usuario U(NOLOCK),Empresa E(NOLOCK)
	WHERE	1  = 1 
	AND		U.ESTADO			=	1 
	AND		U.RUTEMPRESA		=	E.RUT
 	AND		( ( LEN(RTRIM(@RUTEMPRESA))=0) OR ( (LEN(RTRIM(@RUTEMPRESA)) > 0) AND E.RUT  = @RUTEMPRESA) )
	AND		( ( LEN(RTRIM(@USERNAME))=0) OR ( (LEN(RTRIM(@USERNAME)) > 0) AND RTRIM(U.USERNAME) LIKE '%'+RTRIM(@USERNAME) +'%') )
	AND		( ( LEN(RTRIM(@APELLIDOPAT))=0) OR ( (LEN(RTRIM(@APELLIDOPAT)) > 0) AND RTRIM(U.USERNAME) LIKE '%'+RTRIM(@APELLIDOPAT) +'%') )
	AND		( ( @ESTADO=-1) OR ( (@ESTADO <> -1) AND U.ESTADO  = @ESTADO) )
	AND		( ( @INDTOKEN=0) OR ( (@INDTOKEN <> 0) AND EXISTS(SELECT 1 FROM API_USUARIOS API(NOLOCK) WHERE API.USERNAME = U.USERNAME) ) )
	AND		( ( LEN(RTRIM(@TOKEN))=0) OR ( (LEN(RTRIM(@TOKEN)) > 0) AND  EXISTS(SELECT 1 FROM API_USUARIOS API(NOLOCK) WHERE API.USERNAME = U.USERNAME AND RTRIM(API.API_TOKEN) LIKE '%'+RTRIM(@TOKEN) +'%')) ) 



END


