//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LIB.Model.API.API_ENT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class API_ENT : DbContext
    {
        public API_ENT()
            : base("name=API_ENT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_VAL_API_PROF_USERS_LOGIN_Result> SP_VAL_API_PROF_USERS_LOGIN(string pHRASE, string uSER, string pW)
        {
            var pHRASEParameter = pHRASE != null ?
                new ObjectParameter("PHRASE", pHRASE) :
                new ObjectParameter("PHRASE", typeof(string));
    
            var uSERParameter = uSER != null ?
                new ObjectParameter("USER", uSER) :
                new ObjectParameter("USER", typeof(string));
    
            var pWParameter = pW != null ?
                new ObjectParameter("PW", pW) :
                new ObjectParameter("PW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VAL_API_PROF_USERS_LOGIN_Result>("SP_VAL_API_PROF_USERS_LOGIN", pHRASEParameter, uSERParameter, pWParameter);
        }
    
        public virtual ObjectResult<byte[]> SP_GEN_API_PROF_USERS_LOGIN_NEW_PW(string pHRASE, string pW)
        {
            var pHRASEParameter = pHRASE != null ?
                new ObjectParameter("PHRASE", pHRASE) :
                new ObjectParameter("PHRASE", typeof(string));
    
            var pWParameter = pW != null ?
                new ObjectParameter("PW", pW) :
                new ObjectParameter("PW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("SP_GEN_API_PROF_USERS_LOGIN_NEW_PW", pHRASEParameter, pWParameter);
        }
    
        public virtual ObjectResult<string> SP_SEL_API_PROF_USERS_LOGIN_LEE_PW(string pHRASE, string uSER)
        {
            var pHRASEParameter = pHRASE != null ?
                new ObjectParameter("PHRASE", pHRASE) :
                new ObjectParameter("PHRASE", typeof(string));
    
            var uSERParameter = uSER != null ?
                new ObjectParameter("USER", uSER) :
                new ObjectParameter("USER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SEL_API_PROF_USERS_LOGIN_LEE_PW", pHRASEParameter, uSERParameter);
        }
    }
}
